services:
  - type: web
    name: plant-disease-detector
    runtime: python
    plan: free
    rootDir: cnn model
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run main.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
